# Site settings
title: Their Secrets
email: rubiebravos@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rubie.info" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  flowero

# Build settings
markdown: kramdown
permalink: pretty
